name: build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3,9,15,21 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Checkout custom builder
        uses: actions/checkout@v4
        with:
          repository: runetfreedom/domain-list-custom
          path: custom

      - name: Checkout domain-list-community
        uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: community

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./custom/go.mod

      - name: Get and prepare lists
        run: |
          # Скачиваем списки
          curl -sSL https://community.antifilter.download/list/domains.lst > ./community/data/antifilter-download-community
          curl -sSL https://raw.githubusercontent.com/1andrevich/Re-filter-lists/refs/heads/main/domains_all.lst > ./community/data/refilter
          
          # Жесткая очистка от любого мусора (оставляем только латиницу, цифры, точки и дефисы)
          find ./community/data/ -type f -exec sed -i '/^[a-zA-Z0-9.-]*$/!d' {} +
          
          # Создаем файл ru-blocked
          echo "include:antifilter-download-community" > ./community/data/ru-blocked
          echo "include:refilter" >> ./community/data/ru-blocked

      - name: Build geosite.dat
        run: |
          cd custom
          go run ./ --exportlists=ru-blocked,youtube,discord,telegram --datname=geosite.dat --datapath=../community/data

      - name: Prepare publish
        run: |
          mkdir -p publish
          install -Dp ./custom/publish/geosite.dat ./publish/geosite.dat
          (cd ./publish && sha256sum geosite.dat > geosite.dat.sha256sum)

      - name: Release and upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.TAG_NAME }}
          file_glob: true
          file: ./publish/*
          overwrite: true
          make_latest: true

      - name: Push to release branch
        run: |
          cd publish
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
